repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/Bing-su/pre-gommit-hooks
    rev: v2024.06.05
    hooks:
      - id: staticcheck
      - id: golangci-lint
      - id: goimports
      - id: gofumpt
